import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import { 
  faHome,
  faSearch,
  faBell,
  faEnvelope,
  faWallet,
  faUser,
  faHeart,
  faComment,
  faShare,
  faRetweet,
  faEllipsisH,
  faPlus,
  faTimes,
  faCheck,
  faInfoCircle,
  faEdit,
  faCog,
  faSignOutAlt,
  faUsers,
  faHashtag,
  faChartLine,
  faFire,
  faBolt,
  faLink,
  faComments,
  faGlobe,
  faSun,
  faMoon,
  faDownload,
  faChevronDown,
  faUserPlus,
  faUserMinus,
  faUserSlash,
  faUserFriends,
  faImage,
  faCamera,
  faRocket,
  faList,
  faCommentAlt,
  faCalendarAlt,
  faCopy,
  faCheckCircle,
  faExclamationTriangle,
  faCompass,
  faTools,
  faChevronLeft,
  faCircleNotch,
  faSyncAlt,
  faCoins,
  faPaperPlane,
  faChevronUp,
  faUserCheck,
  faLock,
  faEye,
  faFileAlt,
  faBookOpen,
  faRefresh,
  faArrowRight,
  faSpinner,
  faQuestion,
  faUnlock,
  faKey,
  faExclamationCircle,
  faRedo
} from '@fortawesome/free-solid-svg-icons';

import {
  faHeart as faHeartRegular,
  faComment as faCommentRegular,
  faBookmark,
  faUser as faUserRegular
} from '@fortawesome/free-regular-svg-icons';

import {
  faTwitter,
  faGithub,
  faDiscord,
  faTelegram
} from '@fortawesome/free-brands-svg-icons';

export function initializeFontAwesome(library: FaIconLibrary): void {
  // Solid icons
  library.addIcons(
    faHome,
    faSearch,
    faBell,
    faEnvelope,
    faWallet,
    faUser,
    faHeart,
    faComment,
    faShare,
    faRetweet,
    faEllipsisH,
    faPlus,
    faTimes,
    faCheck,
    faExclamationTriangle,
    faInfoCircle,
    faEdit,
    faCog,
    faSignOutAlt,
    faUsers,
    faHashtag,
    faChartLine,
    faFire,
    faBolt,
    faLink,
    faComments,
    faGlobe,
    faSun,
    faMoon,
    faDownload,
    faChevronDown,
    faUserPlus,
    faUserMinus,
    faUserSlash,
    faUserFriends,
    faImage,
    faCamera,
    faRocket,
    faList,
    faCommentAlt,
    faCalendarAlt,
    faCopy,
    faCheckCircle,
    faCompass,
    faTools,
    faChevronLeft,
    faCircleNotch,
    faSyncAlt,
    faCoins,
    faPaperPlane,
    faChevronUp,
    faUserCheck,
    faLock,
    faEye,
    faFileAlt,
    faBookOpen,
    faRefresh,
    faArrowRight,
    faSpinner,
    faQuestion,
    faUnlock,
    faKey,
    faExclamationCircle,
    faRedo
  );

  // Regular icons
  library.addIcons(
    faHeartRegular,
    faCommentRegular,
    faBookmark,
    faUserRegular
  );

  // Brand icons
  library.addIcons(
    faTwitter,
    faGithub,
    faDiscord,
    faTelegram
  );
}